In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
lending_data_df = pd.read_csv('Resources/lending_data.csv')

# Review the DataFrame
lending_data_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

In [3]:
# Checking to seem the imbalance of healthy loans(0) compared to high-risk loans(1) in the dataset
lending_data_df['loan_status'].value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [4]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = lending_data_df['loan_status']

# Separate the X variable, the features
X = lending_data_df.drop(columns = 'loan_status')

In [5]:
# Review the y variable Series
y

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64

In [6]:
# Review the X variable DataFrame
X

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

### Step 3: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)         ## stratify y so that there is an equal amount of 0s (healthy loans) & 1s(high-risk loans) in the training and testing data

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
lr_model = LogisticRegression(random_state=1)

# Fit the model using training data
lr_model.fit(X_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
# Make a prediction using the testing data
test_predictions = lr_model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [10]:
# Generate a confusion matrix for the model
confusion_matrix(y_test, test_predictions)

array([[18679,    80],
       [   67,   558]], dtype=int64)

In [11]:
# Print the classification report for the model
target_names = ["0", "1"]
lg_classification_report = classification_report(test_predictions, y_test, target_names=target_names)
print(lg_classification_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18746
           1       0.89      0.87      0.88       638

    accuracy                           0.99     19384
   macro avg       0.94      0.94      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model demonstrates excellent performance in predicting both healthy (0) and high-risk (1) loans. Notably, the model achieved a perfect score (precision, recall, and F1-score of 1.0) for healthy loans, indicating it flawlessly identified these loans from the features used for training. For high-risk loans, the model maintains a strong performance with a precision of 0.89 and a recall of 0.87. This translates to the model accurately predicting 89% of high-risk loans while correctly classifying 87% of actual high-risk loans, potentially missing 13% that could be misclassified as healthy. While the overall accuracy of 0.99 is very good, it's important to acknowledge the potential class imbalance in the dataset. A model simply predicting all loans as healthy might achieve a very high accuracy score but this disregards the crucial identification of high-risk loans.

In this context, the model effectively addresses both healthy and high-risk loans with high F1-scores (1.0 and 0.88 respectively). However, the 87% recall for high-risk loans warrants further consideration. Misclassifying even a small portion of high-risk loans could lead to significant financial consequences. This highlights an opportunity for potential improvement. However, the current performance demonstrates a strong foundation for a robust credit risk classification model.

---

### K-Nearest Neighbors Model

In [12]:
# Split the dataset
KNN_X_train, KNN_X_test, KNN_y_train, KNN_y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)         ## stratify y so that there is an equal amount of 0s (healthy loans) & 1s(high-risk loans) in the training and testing data

In [13]:
# Create the StandardScaler instance
scaler = StandardScaler()

# Fit the Standard Scaler with the training data
KNN_X_scaler = scaler.fit(KNN_X_train)

# Scale the training data
KNN_X_train_scaled = KNN_X_scaler.transform(KNN_X_train)
KNN_X_test_scaled = KNN_X_scaler.transform(KNN_X_test)

In [14]:
from sklearn.neighbors import KNeighborsClassifier

# Instantiate the model with k = 3 neighbors
knn_model = KNeighborsClassifier(n_neighbors=3)

In [15]:
# Train the model
knn_model.fit(KNN_X_train_scaled, KNN_y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
# Make a prediction using the testing data
knn_test_predictions = knn_model.predict(KNN_X_test_scaled)

In [17]:
# Generate a confusion matrix for the model
confusion_matrix(KNN_y_test, knn_test_predictions)

array([[18677,    82],
       [   47,   578]], dtype=int64)

In [18]:
# Print the classification report for the model
target_names = ["0", "1"]
knn_classification_report = classification_report(knn_test_predictions, KNN_y_test, target_names=target_names)
print(knn_classification_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18724
           1       0.92      0.88      0.90       660

    accuracy                           0.99     19384
   macro avg       0.96      0.94      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Random Forest Model

In [19]:
# Split the dataset
RF_X_train, RF_X_test, RF_y_train, RF_y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)         ## stratify y so that there is an equal amount of 0s (healthy loans) & 1s(high-risk loans) in the training and testing data

In [20]:
# Create the StandardScaler instance
scaler = StandardScaler()

# Fit the Standard Scaler with the training data
RF_X_scaler = scaler.fit(RF_X_train)

# Scale the training data
RF_X_train_scaled = RF_X_scaler.transform(RF_X_train)
RF_X_test_scaled = RF_X_scaler.transform(RF_X_test)

In [21]:
from sklearn.ensemble import RandomForestClassifier

# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=500, random_state=1)

In [22]:
# Train the model
rf_model = rf_model.fit(RF_X_train_scaled, RF_y_train)

In [23]:
# Making predictions using the testing data
rf_test_predictions = rf_model.predict(RF_X_test_scaled)

In [24]:
# Generate a confusion matrix for the model
confusion_matrix(RF_y_test, rf_test_predictions)

array([[18680,    79],
       [   72,   553]], dtype=int64)

In [25]:
# Print the classification report for the model
target_names = ["0", "1"]
rf_classification_report = classification_report(rf_test_predictions, RF_y_test, target_names=target_names)
print(rf_classification_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18752
           1       0.88      0.88      0.88       632

    accuracy                           0.99     19384
   macro avg       0.94      0.94      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Comparing results of each models performance

In [26]:
# Printing out results of each models classification report to compare model performance
print('--------------------------------------------')
print('Logistic Regression Model - Classification Report')
print('--------------------------------------------')
print(lg_classification_report)

print('--------------------------------------------')
print('K-Nearest Nieghbors Model - Classification Report')
print('--------------------------------------------')
print(knn_classification_report)

print('--------------------------------------------')
print('Random Forest Model - Classification Report')
print('--------------------------------------------')
print(rf_classification_report)

--------------------------------------------
Logistic Regression Model - Classification Report
--------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18746
           1       0.89      0.87      0.88       638

    accuracy                           0.99     19384
   macro avg       0.94      0.94      0.94     19384
weighted avg       0.99      0.99      0.99     19384

--------------------------------------------
K-Nearest Nieghbors Model - Classification Report
--------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18724
           1       0.92      0.88      0.90       660

    accuracy                           0.99     19384
   macro avg       0.96      0.94      0.95     19384
weighted avg       0.99      0.99      0.99     19384

--------------------------------------------
Random Forest Model -